// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.17.3
// source: rollout.proto

package protobuff

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RolloutRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Deployment to resume
	DeploymentId string `protobuf:"bytes,1,opt,name=deploymentId,proto3" json:"deploymentId,omitempty"`
	// if true would resume any paused atomic deployment of the main deployment
	All bool `protobuf:"varint,2,opt,name=all,proto3" json:"all,omitempty"`
	// name of the atomic deployment part of the deployment to resume
	Name string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	// type of the atomic deployment part of the deployment to resume
	Type string `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
}

func (x *RolloutRequest) Reset() {
	*x = RolloutRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rollout_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RolloutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RolloutRequest) ProtoMessage() {}

func (x *RolloutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rollout_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RolloutRequest.ProtoReflect.Descriptor instead.
func (*RolloutRequest) Descriptor() ([]byte, []int) {
	return file_rollout_proto_rawDescGZIP(), []int{0}
}

func (x *RolloutRequest) GetDeploymentId() string {
	if x != nil {
		return x.DeploymentId
	}
	return ""
}

func (x *RolloutRequest) GetAll() bool {
	if x != nil {
		return x.All
	}
	return false
}

func (x *RolloutRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RolloutRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

type RolloutResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message        string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	NumberAffected int32  `protobuf:"varint,2,opt,name=numberAffected,proto3" json:"numberAffected,omitempty"`
}

func (x *RolloutResponse) Reset() {
	*x = RolloutResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rollout_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RolloutResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RolloutResponse) ProtoMessage() {}

func (x *RolloutResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rollout_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RolloutResponse.ProtoReflect.Descriptor instead.
func (*RolloutResponse) Descriptor() ([]byte, []int) {
	return file_rollout_proto_rawDescGZIP(), []int{1}
}

func (x *RolloutResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *RolloutResponse) GetNumberAffected() int32 {
	if x != nil {
		return x.NumberAffected
	}
	return 0
}

var File_rollout_proto protoreflect.FileDescriptor

var file_rollout_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x72, 0x6f, 0x6c, 0x6c, 0x6f, 0x75, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x07, 0x72, 0x6f, 0x6c, 0x6c, 0x6f, 0x75, 0x74, 0x22, 0x6e, 0x0a, 0x0e, 0x52, 0x6f, 0x6c, 0x6c,
	0x6f, 0x75, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x22, 0x0a, 0x0c, 0x64, 0x65,
	0x70, 0x6c, 0x6f, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0c, 0x64, 0x65, 0x70, 0x6c, 0x6f, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x10,
	0x0a, 0x03, 0x61, 0x6c, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x03, 0x61, 0x6c, 0x6c,
	0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x22, 0x53, 0x0a, 0x0f, 0x52, 0x6f, 0x6c, 0x6c,
	0x6f, 0x75, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x26, 0x0a, 0x0e, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x41,
	0x66, 0x66, 0x65, 0x63, 0x74, 0x65, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0e, 0x6e,
	0x75, 0x6d, 0x62, 0x65, 0x72, 0x41, 0x66, 0x66, 0x65, 0x63, 0x74, 0x65, 0x64, 0x42, 0x2e, 0x5a,
	0x2c, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x61, 0x72, 0x6d, 0x6f,
	0x72, 0x79, 0x2d, 0x69, 0x6f, 0x2f, 0x64, 0x65, 0x70, 0x6c, 0x6f, 0x79, 0x2d, 0x65, 0x6e, 0x67,
	0x69, 0x6e, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x73, 0x2f, 0x64, 0x65, 0x6e, 0x67, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_rollout_proto_rawDescOnce sync.Once
	file_rollout_proto_rawDescData = file_rollout_proto_rawDesc
)

func file_rollout_proto_rawDescGZIP() []byte {
	file_rollout_proto_rawDescOnce.Do(func() {
		file_rollout_proto_rawDescData = protoimpl.X.CompressGZIP(file_rollout_proto_rawDescData)
	})
	return file_rollout_proto_rawDescData
}

var file_rollout_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_rollout_proto_goTypes = []interface{}{
	(*RolloutRequest)(nil),  // 0: rollout.RolloutRequest
	(*RolloutResponse)(nil), // 1: rollout.RolloutResponse
}
var file_rollout_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_rollout_proto_init() }
func file_rollout_proto_init() {
	if File_rollout_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_rollout_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RolloutRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rollout_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RolloutResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_rollout_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_rollout_proto_goTypes,
		DependencyIndexes: file_rollout_proto_depIdxs,
		MessageInfos:      file_rollout_proto_msgTypes,
	}.Build()
	File_rollout_proto = out.File
	file_rollout_proto_rawDesc = nil
	file_rollout_proto_goTypes = nil
	file_rollout_proto_depIdxs = nil
}
