// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.17.3
// source: environment.proto

package deng

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Environment struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Provider string `protobuf:"bytes,1,opt,name=provider,proto3" json:"provider,omitempty"`
	Account  string `protobuf:"bytes,2,opt,name=account,proto3" json:"account,omitempty"`
	Alias    string `protobuf:"bytes,3,opt,name=alias,proto3" json:"alias,omitempty"`
	// Types that are assignable to Qualifier:
	//	*Environment_Kubernetes
	//	*Environment_Aws
	Qualifier isEnvironment_Qualifier `protobuf_oneof:"qualifier"`
}

func (x *Environment) Reset() {
	*x = Environment{}
	if protoimpl.UnsafeEnabled {
		mi := &file_environment_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Environment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Environment) ProtoMessage() {}

func (x *Environment) ProtoReflect() protoreflect.Message {
	mi := &file_environment_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Environment.ProtoReflect.Descriptor instead.
func (*Environment) Descriptor() ([]byte, []int) {
	return file_environment_proto_rawDescGZIP(), []int{0}
}

func (x *Environment) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *Environment) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *Environment) GetAlias() string {
	if x != nil {
		return x.Alias
	}
	return ""
}

func (m *Environment) GetQualifier() isEnvironment_Qualifier {
	if m != nil {
		return m.Qualifier
	}
	return nil
}

func (x *Environment) GetKubernetes() *KubernetesQualifier {
	if x, ok := x.GetQualifier().(*Environment_Kubernetes); ok {
		return x.Kubernetes
	}
	return nil
}

func (x *Environment) GetAws() *AWSQualifier {
	if x, ok := x.GetQualifier().(*Environment_Aws); ok {
		return x.Aws
	}
	return nil
}

type isEnvironment_Qualifier interface {
	isEnvironment_Qualifier()
}

type Environment_Kubernetes struct {
	Kubernetes *KubernetesQualifier `protobuf:"bytes,4,opt,name=kubernetes,proto3,oneof"`
}

type Environment_Aws struct {
	Aws *AWSQualifier `protobuf:"bytes,5,opt,name=aws,proto3,oneof"`
}

func (*Environment_Kubernetes) isEnvironment_Qualifier() {}

func (*Environment_Aws) isEnvironment_Qualifier() {}

type KubernetesQualifier struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Namespace string `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
}

func (x *KubernetesQualifier) Reset() {
	*x = KubernetesQualifier{}
	if protoimpl.UnsafeEnabled {
		mi := &file_environment_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KubernetesQualifier) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KubernetesQualifier) ProtoMessage() {}

func (x *KubernetesQualifier) ProtoReflect() protoreflect.Message {
	mi := &file_environment_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KubernetesQualifier.ProtoReflect.Descriptor instead.
func (*KubernetesQualifier) Descriptor() ([]byte, []int) {
	return file_environment_proto_rawDescGZIP(), []int{1}
}

func (x *KubernetesQualifier) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

type AWSQualifier struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Region string `protobuf:"bytes,1,opt,name=region,proto3" json:"region,omitempty"`
	Vpc    string `protobuf:"bytes,2,opt,name=vpc,proto3" json:"vpc,omitempty"`
}

func (x *AWSQualifier) Reset() {
	*x = AWSQualifier{}
	if protoimpl.UnsafeEnabled {
		mi := &file_environment_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AWSQualifier) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AWSQualifier) ProtoMessage() {}

func (x *AWSQualifier) ProtoReflect() protoreflect.Message {
	mi := &file_environment_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AWSQualifier.ProtoReflect.Descriptor instead.
func (*AWSQualifier) Descriptor() ([]byte, []int) {
	return file_environment_proto_rawDescGZIP(), []int{2}
}

func (x *AWSQualifier) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *AWSQualifier) GetVpc() string {
	if x != nil {
		return x.Vpc
	}
	return ""
}

var File_environment_proto protoreflect.FileDescriptor

var file_environment_proto_rawDesc = []byte{
	0x0a, 0x11, 0x65, 0x6e, 0x76, 0x69, 0x72, 0x6f, 0x6e, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x65, 0x6e, 0x76, 0x69, 0x72, 0x6f, 0x6e, 0x6d, 0x65, 0x6e, 0x74,
	0x22, 0xd9, 0x01, 0x0a, 0x0b, 0x45, 0x6e, 0x76, 0x69, 0x72, 0x6f, 0x6e, 0x6d, 0x65, 0x6e, 0x74,
	0x12, 0x1a, 0x0a, 0x08, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x12, 0x18, 0x0a, 0x07,
	0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61,
	0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x61, 0x6c, 0x69, 0x61, 0x73, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x61, 0x6c, 0x69, 0x61, 0x73, 0x12, 0x42, 0x0a, 0x0a,
	0x6b, 0x75, 0x62, 0x65, 0x72, 0x6e, 0x65, 0x74, 0x65, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x20, 0x2e, 0x65, 0x6e, 0x76, 0x69, 0x72, 0x6f, 0x6e, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x4b,
	0x75, 0x62, 0x65, 0x72, 0x6e, 0x65, 0x74, 0x65, 0x73, 0x51, 0x75, 0x61, 0x6c, 0x69, 0x66, 0x69,
	0x65, 0x72, 0x48, 0x00, 0x52, 0x0a, 0x6b, 0x75, 0x62, 0x65, 0x72, 0x6e, 0x65, 0x74, 0x65, 0x73,
	0x12, 0x2d, 0x0a, 0x03, 0x61, 0x77, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e,
	0x65, 0x6e, 0x76, 0x69, 0x72, 0x6f, 0x6e, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x41, 0x57, 0x53, 0x51,
	0x75, 0x61, 0x6c, 0x69, 0x66, 0x69, 0x65, 0x72, 0x48, 0x00, 0x52, 0x03, 0x61, 0x77, 0x73, 0x42,
	0x0b, 0x0a, 0x09, 0x71, 0x75, 0x61, 0x6c, 0x69, 0x66, 0x69, 0x65, 0x72, 0x22, 0x33, 0x0a, 0x13,
	0x4b, 0x75, 0x62, 0x65, 0x72, 0x6e, 0x65, 0x74, 0x65, 0x73, 0x51, 0x75, 0x61, 0x6c, 0x69, 0x66,
	0x69, 0x65, 0x72, 0x12, 0x1c, 0x0a, 0x09, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63,
	0x65, 0x22, 0x38, 0x0a, 0x0c, 0x41, 0x57, 0x53, 0x51, 0x75, 0x61, 0x6c, 0x69, 0x66, 0x69, 0x65,
	0x72, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x72, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x12, 0x10, 0x0a, 0x03, 0x76, 0x70, 0x63,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x76, 0x70, 0x63, 0x42, 0x2e, 0x5a, 0x2c, 0x67,
	0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x61, 0x72, 0x6d, 0x6f, 0x72, 0x79,
	0x2d, 0x69, 0x6f, 0x2f, 0x64, 0x65, 0x70, 0x6c, 0x6f, 0x79, 0x2d, 0x65, 0x6e, 0x67, 0x69, 0x6e,
	0x65, 0x2f, 0x61, 0x70, 0x69, 0x73, 0x2f, 0x64, 0x65, 0x6e, 0x67, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_environment_proto_rawDescOnce sync.Once
	file_environment_proto_rawDescData = file_environment_proto_rawDesc
)

func file_environment_proto_rawDescGZIP() []byte {
	file_environment_proto_rawDescOnce.Do(func() {
		file_environment_proto_rawDescData = protoimpl.X.CompressGZIP(file_environment_proto_rawDescData)
	})
	return file_environment_proto_rawDescData
}

var file_environment_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_environment_proto_goTypes = []interface{}{
	(*Environment)(nil),         // 0: environment.Environment
	(*KubernetesQualifier)(nil), // 1: environment.KubernetesQualifier
	(*AWSQualifier)(nil),        // 2: environment.AWSQualifier
}
var file_environment_proto_depIdxs = []int32{
	1, // 0: environment.Environment.kubernetes:type_name -> environment.KubernetesQualifier
	2, // 1: environment.Environment.aws:type_name -> environment.AWSQualifier
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_environment_proto_init() }
func file_environment_proto_init() {
	if File_environment_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_environment_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Environment); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_environment_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*KubernetesQualifier); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_environment_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AWSQualifier); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_environment_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*Environment_Kubernetes)(nil),
		(*Environment_Aws)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_environment_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_environment_proto_goTypes,
		DependencyIndexes: file_environment_proto_depIdxs,
		MessageInfos:      file_environment_proto_msgTypes,
	}.Build()
	File_environment_proto = out.File
	file_environment_proto_rawDesc = nil
	file_environment_proto_goTypes = nil
	file_environment_proto_depIdxs = nil
}
