name: PR Build

on: [ pull_request ]

jobs:
  build:
    name: Build Project
    runs-on: ubuntu-latest
    env:
      BASE_PROJECT: armory-cli
      PR_NUMBER: ${{ github.event.number }}
      PVT_GITHUB_ACCESS_TOKEN: ${{ secrets.PVT_GITHUB_ACCESS_TOKEN }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - uses: actions/setup-go@v2
        with:
          go-version: 1.16.5

      - name: Cache Dependencies
        uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: go-${{ hashFiles('**/go.sum') }}
          restore-keys: go-

      - name: Run Make
        run: |
          make all

      - name: Upload Tests Reports
        if: ${{ always() }}
        uses: actions/upload-artifact@v2
        with:
          name: armory-cli-reports
          path: |
            build/reports/*

      - name: Build & Push Docker Image
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.ARTIFACTORY_USER }}
          password: ${{ secrets.ARTIFACTORY_TOKEN }}
          registry: armory-docker-local.jfrog.io
          repository: armory/${{ env.BASE_PROJECT }}
          add_git_labels: true
          tag_with_sha: true
          build_args: GITHUB_TOKEN=${{ secrets.PVT_GITHUB_ACCESS_TOKEN }},VERSION=PR-${{ env.PR_NUMBER }}

